One gitpod guide
appdev-lessons/gitpod-setup pull request #1
Opened 2023-11-27 18:22 UTC by ananthprayaga

Summary of Changes:
1. Consolidated [https://learn.firstdraft.com/lessons/1](https://learn.firstdraft.com/lessons/1) and (https://learn.firstdraft.com/lessons/48-gitpod-setup)[https://learn.firstdraft.com/lessons/48-gitpod-setup] into one lesson. 

1. The lesson is named Gitpod Guide with four main guides with navigation to respective sections at the top of the page: 
- [Getting started with GitPod](https://learn.firstdraft.com/lessons/248-gitpod-setup#getting-started-with-gitpod)
- [Loading a grades project with GitPod](https://learn.firstdraft.com/lessons/248-gitpod-setup#loading-a-grades-project-with-gitpod)
- [GitHub integration with GitPod](https://learn.firstdraft.com/lessons/248-gitpod-setup#github-integration-with-gitpod)
- [Sharing a GitPod snapshot](https://learn.firstdraft.com/lessons/248-gitpod-setup#sharing-a-gitpod-snapshot)

3. The main changes are within GitHub Integration with Gitpod. Images for steps 1, 2, 3, 4, and 6 are updated with the text changes where necessary. 

Here is the link to the page - https://learn.firstdraft.com/lessons/248-gitpod-setup#github-integration-with-gitpod

2023-11-27 18:29 UTC, bpurinton commented on content.md
> +    ![file](/assets/user-setting.png)
```suggestion
    ![file](/assets/user-setting.png)
    {: .bleed-full }
```

Add the `{: .bleed-full }` tag under this and the other images. They are too small right now.

2023-11-27 18:30 UTC, bpurinton commented on content.md
> +1. Ensure that your organization has permission. If not, click "Grant" next to its name:
We no longer use "organizations", I think this should be changed to "your user settings" or something. It looks like the screenshot image is correct. But there might need to be some instructions for how to get to that page? Like the URL `github.com/<your-username>/settings` or whatever URL that page is from.

2023-11-27 18:34 UTC, bpurinton commented on content.md
> +## GitHub Integration with Gitpod
I'm worried that students will not read the Github integration section since it comes after setting up a project. I think we should move this section up into the "Getting started with Gitpod" section and this list of steps should be inserted into the list of steps above (see my other comment). That will make for a pretty long list of steps, but these are important and they only need to be done once.

2023-11-27 18:38 UTC, bpurinton commented on content.md
> +## Loading a Grades project with Gitpod
Move this section up to the beginning of the lesson, but add this blue-box note:

```markdown
<div class="bg-blue-100 py-1 px-5">

The following is a quick-start for opening a project on Gitpod. **Before you do this,** follow the steps in the [Getting Started With Gitpod](#getting-started-with-gitpod){: target="_self" } section below. Those steps need to be done the very first time you setup Gitpod.
</div>
```

2023-11-27 18:43 UTC, bpurinton requested changes
Few requested changes. Content is mostly good but things need to be re-shuffled.

2023-11-27 21:20 UTC, ananthprayaga commented on content.md
> +1. [Getting started with GitPod](#getting-started-with-gitpod){: target="_self"}
I corrected all instances of Gitpod.

2023-11-27 21:27 UTC, ananthprayaga commented on content.md
> +    ![file](/assets/user-setting.png)
Done

2023-11-27 21:33 UTC, ananthprayaga commented on content.md
> +1. Ensure that your organization has permission. If not, click "Grant" next to its name:
Removed steps 4 and 5 since the update permissions step in step 3 should mostly take care of this.

2023-11-28 16:59 UTC, ananthprayaga commented on content.md
> +## Loading a Grades project with Gitpod
This is completed

2023-11-28 16:59 UTC, ananthprayaga commented on content.md
> +  1. We will create a **workspace** for each project that we work on. Each workspace is based on a GitHub **repository** (i.e., a folder with some code in it; a.k.a., **repo**).
This is completed

2023-11-28 17:00 UTC, ananthprayaga commented on content.md
> +## GitHub Integration with Gitpod
This has been rearranged -some steps have been removed since they were no longer necessary.

2023-11-28 17:06 UTC, ananthprayaga commented
@bpurinton  Does it take time for learn.firstdraft.com to show updates to a branch?

2023-11-30 17:15 UTC, bpurinton approved these changes
LGTM, let's squash and merge this.

2023-11-30 17:45 UTC, merged